name: 'Comentar em Issue'
description: 'Adiciona um comentário a uma issue do GitHub'
inputs:
  GITHUB_TOKEN:
    description: 'Token de autenticação do GitHub'
    required: true
  ISSUE_ID:
    description: 'ID da issue a ser comentada'
    required: true
  COMMENT:
    description: 'Conteúdo do comentário'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.GITHUB_TOKEN }}'
    - '${{ inputs.ISSUE_ID }}'
    - '${{ inputs.COMMENT }}'
    - '${{ inputs.GITHUB_REPOSITORY }}'